version: "3.9"
services:
  jenkins:
    build: .
    networks:
      - jenkins-network
    ports:
      - "4000:8080"
      - "50000:50000"
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - "jenkins-docker-certs:/certs/client:ro"
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client 
      - DOCKER_TLS_VERIFY=1
    restart: on-failure
  
  networks:
   jenkins-network: 
