version: "3.9"
services:
  jenkins:
    build: .
    ports:
      - "4000:8080"
      - "50000:50000"
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
  
volumes:
  jenkins-data:

